name: New Test Workflow

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2

      - name: Add PR Comment
        uses: mshick/add-pr-comment@v2
        with:
          message: I am a successful request!!!